# Generated by Django 4.0.6 on 2022-09-13 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.DecimalValidator(6, 9)])),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.DecimalValidator(6, 9)])),
                ('sido', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('sigungu', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('doro', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('doro_code', models.CharField(max_length=10)),
                ('sangse', models.CharField(max_length=165, null=True, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣0-9_]+\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=165)),
                ('sub_names', models.CharField(max_length=300, null=True)),
                ('is_operated', models.BooleanField(default=True)),
                ('is_franchising', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hours', models.JSONField(blank=True, default=dict, null=True)),
                ('sns', models.JSONField(blank=True, default=dict, null=True)),
                ('registrant', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_image', to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_menu_image',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('price', models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafe.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='cafe.cafe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cafe',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddField(
            model_name='address',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='cafe.cafe'),
        ),
        migrations.AddConstraint(
            model_name='menuimage',
            constraint=models.UniqueConstraint(fields=('image_url', 'cafe'), name='unique_image_url_cafe'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name', 'cafe'), name='unique_name_cafe'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.UniqueConstraint(fields=('branch_name', 'cafe'), name='unique_branch_name_cafe'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('latitude', 'longtitude'), name='unique_latitude_longtitude'),
        ),
    ]
