# Generated by Django 4.0.6 on 2022-09-29 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_name', models.CharField(max_length=165)),
                ('is_operated', models.SmallIntegerField(default=True)),
                ('is_franchising', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('hours', models.JSONField(blank=True, default=dict, null=True)),
                ('sns', models.JSONField(blank=True, default=dict, null=True)),
                ('registrant', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='cafe.cafe')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.DecimalValidator(6, 9)])),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.DecimalValidator(6, 9)])),
                ('sido', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('sigungu', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('doro', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣_]+\\Z')])),
                ('doro_code', models.CharField(max_length=10)),
                ('sangse', models.CharField(max_length=165, null=True, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣0-9_]+\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='franchise', serialize=False, to='cafe.cafe')),
                ('branch_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('manu_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_image', to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_menu_image',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('price', models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafe.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeSubName',
            fields=[
                ('sub_name_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe_sub_name', to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_sub_name',
            },
        ),
        migrations.AddConstraint(
            model_name='cafe',
            constraint=models.UniqueConstraint(fields=('main_name',), name='unique_main_name'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name', 'cafe'), name='unique_name_cafe'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.UniqueConstraint(fields=('branch_name', 'cafe'), name='unique_branch_name_cafe'),
        ),
        migrations.AddConstraint(
            model_name='cafesubname',
            constraint=models.UniqueConstraint(fields=('sub_name', 'cafe'), name='unique_sub_name_cafe'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('latitude', 'longtitude'), name='unique_latitude_longtitude'),
        ),
    ]
