# Generated by Django 4.0.6 on 2022-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuimage',
            name='unique_image_url_cafe',
        ),
    ]
