# Generated by Django 4.0.6 on 2022-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='sub_names',
        ),
    ]
