# Generated by Django 4.0.6 on 2022-09-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cafe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='cafe.cafe'),
        ),
    ]
