# Generated by Django 4.0.6 on 2022-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_menuimage_unique_image_url_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
