# Generated by Django 4.0.6 on 2022-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_sub_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafesubname',
            old_name='cafe_subname_id',
            new_name='sub_name_id',
        ),
        migrations.AddConstraint(
            model_name='cafesubname',
            constraint=models.UniqueConstraint(fields=('sub_name', 'cafe'), name='unique_sub_name_cafe'),
        ),
        migrations.AlterModelTable(
            name='cafesubname',
            table='cafe_sub_name',
        ),
    ]
