# Generated by Django 4.0.6 on 2022-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_menu_detail_id_alter_address_cafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
