# Generated by Django 4.0.6 on 2022-10-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_franchise_cafe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='is_franchising',
            new_name='is_franchise',
        ),
    ]
