# Generated by Django 4.0.6 on 2022-09-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_address_update_date_alter_menu_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_detail_id',
        ),
    ]
