# Generated by Django 4.0.6 on 2022-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_cafe_subname_id_cafesubname_sub_name_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafesubname',
            name='sub_name',
            field=models.CharField(max_length=1000),
        ),
    ]
