# Generated by Django 4.0.6 on 2022-10-10 08:05

import cafe.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_rename_is_franchising_cafe_is_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_id',
            field=cafe.models.UnsignedBigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cafesubname',
            name='sub_name_id',
            field=cafe.models.UnsignedBigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_id',
            field=cafe.models.UnsignedBigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='manu_image_id',
            field=cafe.models.UnsignedBigAutoField(primary_key=True, serialize=False),
        ),
    ]
