# Generated by Django 4.0.6 on 2022-09-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_menu_menu_detail_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('latitude', 'longtitude', 'cafe'), name='unique_latitude_longtitude_cafe'),
        ),
        migrations.AddConstraint(
            model_name='cafe',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name', 'cafe'), name='unique_name_cafe'),
        ),
    ]
