# Generated by Django 4.0.6 on 2022-10-13 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_cafe_cafe_id_alter_cafesubname_sub_name_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafesubname',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name', to='cafe.cafe'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')]),
        ),
    ]
