# Generated by Django 4.0.6 on 2022-11-01 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_cafesubname_cafe_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='main_name',
            field=models.CharField(max_length=165, validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[-ㄱ-힣a-zA-Z0-9_]+\\Z')]),
        ),
    ]
